### ISSUE TITLE
Weird behaviour after mixup with keys

### ISSUE THREAD

**Issue by tetris4** [kontalk/androidclient#1127] opened 2017-12-30 19:09 UTC
Instead of retrieving my key, I accidentally registered a second key. I then reverted back to my original key but now experience the following weird behavior:

When I send a message to my friends phone:
- she can properly see my message
- she gets a red prompt bar at the bottom that my key has changed
- if she taps on the prompt and selects identity it still shows my old key
- no matter how many times she accepts the (old) key, she keeps getting the `key has changed` notification. 

When she sends me a message, I receive the message but I can't read it, it only says 'encrypted' in a bubble.

I tried refreshing the contacts on both devices several times but it didn't help.

Kontalk version: We are both running 4.1.2, me on f-droid and she on the google play version.
Android version: Me on LineageOS 12.1 (Android 5.1.1) and she on 7.0.
Device model: I am using a Samsung Galaxy Note 1 and she is using a Huawei P8 Lite 2017.

**Comment by daniele-athome** [comment] 2017-12-31 15:50
This is a long-standing bug that should have been fixed a few releases ago but apparently didn't :-(
Her app is using your old key to encrypt messages to you therefore you can't decrypt them.

Since the problem is actually on her side, I don't remember if you already asked her to delete her app data (she will lose all messages though). That should clear any leftover from previous versions.
If she has root access and you don't want to lose the messages:

* force stop Kontalk
* delete `/data/data/org.kontalk/databases/keys.db`
* start Kontalk again

In both cases, trust settings will be cleared and she'll have to trust all keys again (but that's what we want actually). Now that I think about it, I should make a maintenance preference to do just that.

**Comment by tetris4** [comment] 2017-12-31 16:17
Force stop was grayed out on her phone, so I just cleared the data. There was no org.kontalk folder, probably got deleted while clearing the data. I started Kontalk again, refreshed contacts, and voila, it works! 👍 Thanks @daniele-athome!

Since you tagged this as a bug, am leaving it open so it can be tackled in the future.

**Comment by daniele-athome** [comment] 2018-07-22 19:47
Closed by #1171.

**Closed by daniele-athome** 2018-07-22 19:47 UTC
Labels: bug
