### ISSUE TITLE
Compressed images don't store EXIF rotation

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#231] opened 2014-10-14 16:13 UTC
Kontalkversion 3,0 beta2
Androidversion 2.3.6

Steps to reproduce:

-choose compression (large, medium or small)
-Send image 
-Received image thumbnail will be shown correct
-download image
-open image via galarie of Android
-image will be shown turned 90°

See also attached Screenshots
![sc20141013-200152](https://cloud.githubusercontent.com/assets/6864851/4632492/2999df38-53be-11e4-8976-f40cd2ab9d1e.png)
![sc20141013-200209](https://cloud.githubusercontent.com/assets/6864851/4632493/299b83ce-53be-11e4-820f-1b756dcf5647.png)

**Comment by juanito003** [comment] 2015-06-30 08:55
Could you reopen this issue?
It seems that in latest Kontalk Android 3.0.1 all pictures shared in portrait mode are not rotated, in thumbnails and once downloaded.

**Comment by daniele-athome** [comment] 2015-06-30 09:04
Sure, I'll do some tests.

**Comment by utack** [comment] 2015-07-02 15:47
Can confirm this

**Comment by daniele-athome** [comment] 2015-07-05 11:28
@juanito003 can you send me **by email** (not here, it may be modified by GitHub CDN) the original picture that has this problem (or just shoot another one that does the job)? I'm afraid I can't reproduce the issue on my device.

**Comment by juanito003** [comment] 2015-07-07 19:48
Hi I tried again and it works fine in the latest version. It must have been in a previous version. You can close the issue. Thanks.

**Closed** 2015-07-08 08:55 UTC
Labels: bug
