### ISSUE TITLE
NPE when opening messages

### ISSUE THREAD

**Issue by forkoz** [kontalk/androidclient#1158] opened 2018-03-17 15:04 UTC
### Expected behavior
Open Message, see the chat
### Actual behavior
Get a null pointer exception.

### Steps to reproduce
1. open message

### Environment

Kontalk version: 4.1.3 github

Android version: 4.4.4

Device model: Galaxy S3

### Logs

```
E/AndroidRuntime( 3794): FATAL EXCEPTION: main
E/AndroidRuntime( 3794): Process: org.kontalk, PID: 3794
E/AndroidRuntime( 3794): java.lang.NullPointerException
E/AndroidRuntime( 3794):        at org.kontalk.ui.view.BaseMessageTheme.setIncom
ing(BaseMessageTheme.java:146)
E/AndroidRuntime( 3794):        at org.kontalk.ui.view.SimpleMessageTheme.setInc
oming(SimpleMessageTheme.java:79)
E/AndroidRuntime( 3794):        at org.kontalk.ui.view.MessageListItem.bind(Mess
ageListItem.java:133)
E/AndroidRuntime( 3794):        at org.kontalk.ui.adapter.MessageListAdapter.bin
dView(MessageListAdapter.java:87)
E/AndroidRuntime( 3794):        at android.support.v4.widget.CursorAdapter.getVi
ew(CursorAdapter.java:273)
E/AndroidRuntime( 3794):        at android.widget.HeaderViewListAdapter.getView(
HeaderViewListAdapter.java:220)
E/AndroidRuntime( 3794):        at android.widget.AbsListView.obtainView(AbsList
View.java:2283)
E/AndroidRuntime( 3794):        at android.widget.ListView.makeAndAddView(ListVi
ew.java:1790)
E/AndroidRuntime( 3794):        at android.widget.ListView.fillUp(ListView.java:
725)
E/AndroidRuntime( 3794):        at android.widget.ListView.layoutChildren(ListVi
ew.java:1611)
E/AndroidRuntime( 3794):        at android.widget.AbsListView.onLayout(AbsListVi
ew.java:2113)
E/AndroidRuntime( 3794):        at android.view.View.layout(View.java:14834)
E/AndroidRuntime( 3794):        at android.view.ViewGroup.layout(ViewGroup.java:
4631)
E/AndroidRuntime( 3794):        at android.widget.LinearLayout.setChildFrame(Lin
earLayout.java:1671)
E/AndroidRuntime( 3794):        at android.widget.LinearLayout.layoutVertical(Li
nearLayout.java:1525)
E/AndroidRuntime( 3794):        at android.widget.LinearLayout.onLayout(LinearLa
yout.java:1434)
E/AndroidRuntime( 3794):        at android.view.View.layout(View.java:14834)
E/AndroidRuntime( 3794):        at android.view.ViewGroup.layout(ViewGroup.java:
4631)
E/AndroidRuntime( 3794):        at android.widget.RelativeLayout.onLayout(Relati
veLayout.java:1055)
E/AndroidRuntime( 3794):        at android.view.View.layout(View.java:14834)
E/AndroidRuntime( 3794):        at android.view.ViewGroup.layout(ViewGroup.java:
4631)
E/AndroidRuntime( 3794):        at android.widget.FrameLayout.layoutChildren(Fra
meLayout.java:453)
E/AndroidRuntime( 3794):        at android.widget.FrameLayout.onLayout(FrameLayo
ut.java:388)
E/AndroidRuntime( 3794):        at android.view.View.layout(View.java:14834)
E/AndroidRuntime( 3794):        at android.view.ViewGroup.layout(ViewGroup.java:
4631)
E/AndroidRuntime( 3794):        at android.widget.LinearLayout.setChildFrame(Lin
earLayout.java:1671)
E/AndroidRuntime( 3794):        at android.widget.LinearLayout.layoutVertical(Li
nearLayout.java:1525)
E/AndroidRuntime( 3794):        at android.widget.LinearLayout.onLayout(LinearLa
yout.java:1434)
E/AndroidRuntime( 3794):        at android.view.View.layout(View.java:14834)
E/AndroidRuntime( 3794):        at android.view.ViewGroup.layout(ViewGroup.java:
4631)
E/AndroidRuntime( 3794):        at android.widget.FrameLayout.layoutChildren(Fra
meLayout.java:453)
E/AndroidRuntime( 3794):        at android.widget.FrameLayout.onLayout(FrameLayo
ut.java:388)
E/AndroidRuntime( 3794):        at android.view.View.layout(View.java:14834)
E/AndroidRuntime( 3794):        at android.view.ViewGroup.layout(ViewGroup.java:
4631)
E/AndroidRuntime( 3794):        at android.widget.FrameLayout.layoutChildren(Fra
meLayout.java:453)
E/AndroidRuntime( 3794):        at android.widget.FrameLayout.onLayout(FrameLayo
ut.java:388)
E/AndroidRuntime( 3794):        at android.view.View.layout(View.java:14834)
E/AndroidRuntime( 3794):        at android.view.ViewGroup.layout(ViewGroup.java:
4631)
E/AndroidRuntime( 3794):        at android.widget.FrameLayout.layoutChildren(Fra
meLayout.java:453)
E/AndroidRuntime( 3794):        at android.widget.FrameLayout.onLayout(FrameLayo
ut.java:388)
E/AndroidRuntime( 3794):        at android.view.View.layout(View.java:14834)
E/AndroidRuntime( 3794):        at android.view.ViewGroup.layout(ViewGroup.java:
4631)
E/AndroidRuntime( 3794):        at android.widget.LinearLayout.setChildFrame(Lin
earLayout.java:1671)
E/AndroidRuntime( 3794):        at android.widget.LinearLayout.layoutVertical(Li
nearLayout.java:1525)
E/AndroidRuntime( 3794):        at android.widget.LinearLayout.onLayout(LinearLa
yout.java:1434)
E/AndroidRuntime( 3794):        at android.view.View.layout(View.java:14834)
E/AndroidRuntime( 3794):        at android.view.ViewGroup.layout(ViewGroup.java:
4631)
E/AndroidRuntime( 3794):        at android.widget.FrameLayout.layoutChildren(Fra
meLayout.java:453)
E/AndroidRuntime( 3794):        at android.widget.FrameLayout.onLayout(FrameLayo
ut.java:388)
E/AndroidRuntime( 3794):        at android.view.View.layout(View.java:14834)
E/AndroidRuntime( 3794):        at android.view.ViewGroup.layout(ViewGroup.java:
4631)
E/AndroidRuntime( 3794):        at android.view.ViewRootImpl.performLayout(ViewR
ootImpl.java:1983)
E/AndroidRuntime( 3794):        at android.view.ViewRootImpl.performTraversals(V
iewRootImpl.java:1740)
E/AndroidRuntime( 3794):        at android.view.ViewRootImpl.doTraversal(ViewRoo
tImpl.java:996)
E/AndroidRuntime( 3794):        at android.view.ViewRootImpl$TraversalRunnable.r
un(ViewRootImpl.java:5600)
E/AndroidRuntime( 3794):        at android.view.Choreographer$CallbackRecord.run
(Choreographer.java:761)
E/AndroidRuntime( 3794):        at android.view.Choreographer.doCallbacks(Choreo
grapher.java:574)
E/AndroidRuntime( 3794):        at android.view.Choreographer.doFrame(Choreograp
her.java:544)
E/AndroidRuntime( 3794):        at android.view.Choreographer$FrameDisplayEventR
eceiver.run(Choreographer.java:747)
E/AndroidRuntime( 3794):        at android.os.Handler.handleCallback(Handler.jav
a:733)
E/AndroidRuntime( 3794):        at android.os.Handler.dispatchMessage(Handler.ja
va:95)
E/AndroidRuntime( 3794):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3794):        at android.app.ActivityThread.main(ActivityThrea
d.java:5146)
E/AndroidRuntime( 3794):        at java.lang.reflect.Method.invokeNative(Native
Method)
W/ActivityManager(  748):   Force finishing activity org.kontalk/.ui.ComposeMess
age
W/ActivityManager(  748):   Force finishing activity org.kontalk/.ui.Conversatio
nsActivity
```

### Other

4.1.2 didn't have the problem

**Comment by daniele-athome** [comment] 2018-03-18 16:43
Duplicate of #1142. I'm going to release 4.1.4 today if all tests go well :-)

**Closed by daniele-athome** 2018-03-18 16:43 UTC
Labels: duplicate
