### ISSUE TITLE
http:// changed to emoticon

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#1082] opened 2017-10-14 11:44 UTC
### Expected behaviour
Send webadresses with http://

### Actual behavior
If I enable Text smilie to graphic the, part "http:/" will chaged to a emoticon

### Steps to reproduce
1. enable Text smilie to graphic
2. open a chat and add http://kontalk.org via copy and paste
3. Set the cursor ahead the first charter of http
4. Press Enter

### Environment

Kontalk version: 4.1.0 beta 4 ( Google Play)

Android version: 7.0

Device model: Huawei nova

**Comment by daniele-athome** [comment] 2017-10-14 12:10
Thanks for reporting!

**Comment by daniele-athome** [comment] 2017-10-14 13:02
It seemed obvious at first, but now that i'm trying to reproduce this, I don't think I get it.

I tried as you stated:

* pasted http://kontalk.org
* moved cursor before the first "h"
* pressed enter (as in enter/newline key)

The whole text was pushed by a line and nothing happened. Am I doing something wrong here?

**Comment by daniele-athome** [comment] 2017-10-14 13:03
By the way, what keyboard are you using?

**Comment by webratte** [comment] 2017-10-14 13:52
You do it the same way like I did.

I will make a few screenshots later to illustrate if you like.

I use the standard keyboard of my huawei phone.

 https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin

**Comment by webratte** [comment] 2017-10-14 13:57
You enabled the option "text smilies to graphics" I suppose.

Am 14. Oktober 2017 15:02:44 MESZ schrieb Daniele Ricci <notifications@github.com>:

**Comment by daniele-athome** [comment] 2017-10-14 14:20
> You enabled the option "text smilies to graphics" I suppose.

Yes.

**Comment by webratte** [comment] 2017-10-14 16:20
I'm not sure if it's possible to send pictures via mail to a github issue.

I try it.

**Comment by webratte** [comment] 2017-10-14 18:12
Here are the screenshots:

Before

![before](https://user-images.githubusercontent.com/6864851/31578137-4b264610-b11b-11e7-9370-523afad91eb7.png)

and after press Enter

![after](https://user-images.githubusercontent.com/6864851/31578122-1910b980-b11b-11e7-9cc8-e16e59ca167b.png)

**Comment by 115ek** [comment] 2017-10-16 17:04
Very intersting. I also had this issue (and it was really clear that it will happen with my algorithm...), but 82fc058cac7c54d701682c8cd1887c6d38bf3133 fixed it for me. It seems that the `http`isn't recognized in your example. I'll look into it :)

**Comment by 115ek** [comment] 2017-10-17 07:01
@webratte 
Can you install another keyboard from the store for testing it?

**Comment by webratte** [comment] 2017-10-17 16:12
I have just tried a other keyboard from Play store.
With this keyboard it's all OK.

So it seems related to my standard keyboard.

Maybe you should test it with this keyboard (link to play store in previous post of me).

**Comment by 115ek** [comment] 2017-10-17 17:58
Okay, I'm able to reproduce it with the google keyboard. I'll try to install it in the emulator for debugging...

**Comment by 115ek** [comment] 2017-10-18 09:07
By disabling keyboard suggestions and autocorrection in google keyboard settings the problem disappears. And the AOSP keyboard doesn't have this issues. Maybe it's a problem of the google keyboard? @daniele-athome : any idea?

**Comment by daniele-athome** [comment] 2017-10-30 22:53
Not much full of ideas at the moment I'm afraid. But it seems to be related to the input given to the EditText. The behaviour could actually be correct, I mean from a strictly technical point of view. Probably for short a moment, the three characters forming the smiley become separated and emoji is formed.

Anyway, this method could use an improvement, for example the transformation could be triggered by a word boundary (e.g. a space after the smiley). @115ek what do you think? Would something like that at least mitigate this issue?

**Comment by 115ek** [comment] 2017-10-31 11:12
Heyho, I made a quick fix for our problem. #1087 
@daniele-athome what do you think?

**Comment by daniele-athome** [comment] 2017-10-31 21:00
I've just merged it, thank you!
I'll close this now, feel free to reopen after 4.1.0 release.

**Closed by daniele-athome** 2017-10-31 21:00 UTC
Labels: bug
