### ISSUE TITLE
Feature request: Show other person's accepted personal key in chat

### ISSUE THREAD

**Issue by jluttine** [kontalk/androidclient#1083] opened 2017-10-16 12:36 UTC
I have Kontalk on two phones. On the other one, I have already made contact with another person and we have encrypted chat. Now, in the other phone, I'd like to verify that the not-yet-verified fingerprint of that same person is the same. Where can I see the personal key of a person that I'm already having encrypted chat? I can see the personal key on the phone that asks for verification but I can't find the key from the phone that has already verified that person. Thanks for any help!

**Comment by 115ek** [comment] 2017-10-16 17:20
As a workaround you can create a group with the person you want to have the key from. Then go into the groupchat --> options --> group info --> click the person --> find the key.
Remove the group if you want. But it would be great to have this feature available also in a two person chat indeed.

**Comment by webratte** [comment] 2017-10-16 17:49
@jluttine 
The correct place for questions like this is our Forum https://forum.kontalk.org/

Here (https://github.com/kontalk/androidclient/issues/) you should only report bugs and not ask for support.

But still:
Currently it's not possible to see the fingerprint for already accepted keys.
The easiest way is, to ask your friend for his keys fingerprint (e.G. by phone call). Hi can find it:
* start Kontalk
* click the three dot menu
* click "my personal key"

**Comment by jluttine** [comment] 2017-10-16 19:10
@webratte Ok! I'll turn this into a bug report / feature request. Add a possibility to see the personal key of the person I'm chatting with and whose key I've already accepted.

**Comment by daniele-athome** [comment] 2017-10-18 09:02
That's something that Kontalk is indeed missing. Duplicate of #456.

**Closed by daniele-athome** 2017-10-18 09:02 UTC
Labels: duplicate
