### ISSUE TITLE
make a  "server user" and use it to broadcast important information to everyone

### ISSUE THREAD

**Issue by h-2** [kontalk/androidclient#339] opened 2015-03-06 14:48 UTC
It would be really great, if there were a "kontalk.net user" on the server that informs all users
  * if the servers are going down for maintenance 
  * if the protocol has been updated in a way were they *must* update to be able to chat with others.

Especially the second point I encountered again with the 3.0-beta8. I can't speak with my contacts and have to explain to them by other means (SMS) that they have to update their Kontalk...

Thanks!

**Comment by daniele-athome** [comment] 2015-03-06 14:57
Duplicate of kontalk/tigase-extension#25.

As for protocol instabilities, we will make an effort to make them happen as few times as possible from now on. I'm sorry for any inconvience, but beta releases were changing very rapidly and often.

**Closed by daniele-athome** 2015-03-06 14:57 UTC
Labels: duplicate

**Comment by h-2** [comment] 2015-03-06 15:05
Ah, ok, good to see there already is a ticket! Thank you!
