### ISSUE TITLE
Audio notification on message in conversation

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#531] opened 2015-08-05 15:54 UTC
I've been trying Telegram for a bit, and I noticed that when you send a message, or when you receive a message in the current conversation, a soft sound is played. This is not the default notification sound and a lot quieter in volume, but very useful to know you have a new message if you've just put your phone down without turning off the screen. I think a feature like this could be useful for Kontalk as well.

**Comment by TheLastProject** [comment] 2015-08-05 15:56
The Telegram sound files in question are here, to give you an idea:
Incoming: https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/res/raw/sound_in.wav
Outgoing: https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/res/raw/sound_out.wav

**Comment by daniele-athome** [comment] 2015-08-06 08:17
Thanks for the examples. Duplicate of #75.

**Closed by daniele-athome** 2015-08-06 08:17 UTC
Labels: duplicate
