### ISSUE TITLE
Featurerequest: Add option "Hide the whole onlinestate"

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#1081] opened 2017-10-14 05:34 UTC
I think this would be a nice privacy feature.

The best way would be "per chat or user"

But I also would like it as a global option.

I hope it's not a duplicate.

**Comment by OffifialMITX** [comment] 2017-10-14 06:51
From my viewpoint that would mean that tge sender also wouldn't see whether their message was delivered or not.

On October 14, 2017 7:34:07 AM GMT+02:00, webratte <notifications@github.com> wrote:
>I think this would be a nice privacy feature.
>
>The best way would be "per chat or user"
>
>But I also would like it as a global option.
>
>I hope it's not a duplicate.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/1081

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by webratte** [comment] 2017-10-14 09:57
I think on a solution like in Threema implemented.

No online state (currently activ and so om), no last seen. 

But delivered message and (as option) reading message and writing... messsage.

**Comment by daniele-athome** [comment] 2017-10-14 12:13
Duplicate of #342 if I understand correctly.

**Closed by daniele-athome** 2017-10-14 12:13 UTC
Labels: duplicate

**Comment by webratte** [comment] 2017-10-14 13:39
Yes, your right.
Sorry.
