### ISSUE TITLE
New personal key not accepted by server: "Invalid revocation key"

### ISSUE THREAD

**Issue by abika** [kontalk/androidclient#621] opened 2016-01-12 18:15 UTC
Regenerating the personal key does not work (anymore). 

The key is successfully created but the server returns an error message:
```
01-12 13:06:29.958 1892-7673/org.kontalk D/SMACK: SENT (4): <iq to='beta.kontalk.net' id='94N66-58' type='set'><query xmlns='jabber:iq:register'><x xmlns='jabber:x:data' type='submit'><field var='FORM_TYPE' type='hidden'><value>http://kontalk.org/protocol/register#key</value></field><field label='Public key' var='publickey' type='text-single'><value>mQENBF ... 2C8K2g=</value></field></x></query></iq>
01-12 13:06:30.068 1892-7674/org.kontalk D/SMACK: RECV (4): <iq to="9352...@beta.kontalk.net/810eb5848f151178" id="94N66-58" type="error" xmlns="jabber:client" from="beta.kontalk.net"><error type="auth" code="403"><forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Invalid revocation key.</text></error></iq>
```

**Comment by daniele-athome** [comment] 2016-01-12 19:20
Thanks for reporting, it's most probably a server issue. I'll investigate tomorrow.

**Comment by daniele-athome** [comment] 2016-01-13 10:13
Ok I was wrong, the problem is in the app. The outgoing packet is missing the revoked key. Investigating...

**Comment by daniele-athome** [comment] 2016-01-13 10:22
Weird bug... are you using 3.1.1?

**Comment by daniele-athome** [comment] 2016-01-13 20:46
Latest master does send the revoked key but that is not accepted by the server, so I guess your log was just incomplete? I'm checking what is happening and get back to you.

**Comment by daniele-athome** [comment] 2016-01-13 22:35
Fixed in kontalk/tigase-extension@ef3f06986f677cd2208ac84c55e03d1866fb450f and server rebuilding now.

**Closed by daniele-athome** 2016-01-13 22:35 UTC
Labels: bug

**Comment by abika** [comment] 2016-01-13 23:04
The log was from 3.1.1 and not master. I'll try again when the server is online again. Does this mean it will still not work with the missing revocation key in 3.1.1?

**Comment by daniele-athome** [comment] 2016-01-14 08:37
It should work with 3.1.1 too, no code was touched in the client for that part since. The bug was in the server, in the new key management part (I stopped using GPG as key storage - it's too slow, I use it only for the registration).

**Comment by abika** [comment] 2016-01-14 15:02
well, thanks for the quick fix. But I had to re-import my account for the emulator, and somehow a verification code is needed again when importing - I can't verify it, the number belongs to a friend. Will check again with another phone...

**Comment by daniele-athome** [comment] 2016-01-14 16:02
The server will ask for verification when the last key used to login was different. Maybe that is your case?
