### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by Megver83** [kontalk/androidclient#978] opened 2017-03-15 17:27 UTC
Hi, is it possible that kontalk can have markdown support? at least basic markdown, like bold, italic, etc.

**Comment by OffifialMITX** [comment] 2017-03-16 07:19
There's an issue about this already, try searching for markdown.

**Comment by daniele-athome** [comment] 2017-03-16 10:05
Duplicate of #801.

**Closed by daniele-athome** 2017-03-16 10:05 UTC
Labels: duplicate
