### ISSUE TITLE
Bug: could not receive all messages in a group

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#921] opened 2017-01-02 14:58 UTC
### Expected behavior
All group members should receive all messages

### Actual behavior
In a group with 3 members one member did not receive one message. It's not the first message in this group. All following messages will received from all members.

### Steps to reproduce
Currently I have not idea how to reproduce. I will try to find out what happens.
Maybe other people run into the same issue and can report.

### Environment

Kontalk version: all have the same 4.0.0 Beta 5 (217)
Android version: 6.0.1

Device model: Sender and receiver who has not received the message: Sony Xperia M4 Aqua

### Logs

No logs because it's to late :-(

**Comment by webratte** [comment] 2017-01-02 15:09
BTW. It would be good if I would have the second check mark if all members received all messages. 
So I can be sure there is no info is lost.

**Comment by OffifialMITX** [comment] 2017-01-02 16:50
I'm not sure how this is possible but i had a double tick in a group chat once... (beta4)

**Comment by daniele-athome** [comment] 2017-01-04 12:43
Delivery confirmation is currently disabled in groups because it needs to account for multiple users, that is, only when all users have received the message it should be double-ticked - and that is not implemented yet.

As for your issue @webratte, I've been trying for months to increase the reliability of message delivery in Tigase, a great deal of progress was made recently, still there seems to be problems.
It's very hard to debug this issue because it happens only during severe network problems (e.g. connecting and disconnecting continuously because of bad network coverage), and it's hard to produce such problems in a controlled environment. I'll do some more tests on the server, but for now I'm closing this since the problem is not with the Android client. I've opened kontalk/tigase-extension#74.

**Closed by daniele-athome** 2017-01-04 12:43 UTC
