### ISSUE TITLE
allow per contact encryption settings

### ISSUE THREAD

**Issue by pravi** [kontalk/androidclient#494] opened 2015-07-05 10:34 UTC
Since kontalk is built on xmpp, I was trying to use a regular xmpp id to talk to kontalk. Since kontalk does not implement xep 0027 key announcement, conversations could not initiate an openpgp session and kontalk could not find openpgp key announced by conversations. So I want to disable encryption only for select contacts. Please add such an option.

**Comment by daniele-athome** [comment] 2015-07-05 10:36
Duplicate of #271.

**Closed by daniele-athome** 2015-07-05 10:36 UTC
Labels: duplicate
