### ISSUE TITLE
Wrong orientation of received photos

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#649] opened 2016-02-13 12:06 UTC
Kontalkversion 3.1.3
Androidversion: 5.0

Steps to reproduce:
-Open Kontallk
-Choose a Contact
-Choose the Paper clip icon (add attachment)
-Choose camera
-take a photo
-send

Now the thumbnail is turned 90° to left.
The receiver also get the photo 90° to left.

This is only happens if I take the photo the described way.

If I choose the picture from gallery or share it from gallery via Kontalk the orientation is correct.

**Comment by webratte** [comment] 2016-02-13 12:25
It seems it's only happens if I take the photo in Portrait Modus.
In landscape Modus the orientation is correct.

**Comment by daniele-athome** [comment] 2016-02-13 17:58
Thanks @webratte, I'll check for a fix soon.

**Comment by daniele-athome** [comment] 2016-04-02 12:28
I can't reproduce it by using Motorola Camera or Open Camera. Can you send me a picture shot by your camera app that way? I'll need the original file so please send it using e-mail (I don't know if GitHub processes it in some way).

**Comment by webratte** [comment] 2016-04-02 14:22
I use the standard camera app of Sony Xperia M4 Aqua.
The picture I will send in a few minutes.

**Comment by daniele-athome** [comment] 2016-04-03 19:05
Fixed in 9b03f1b77a12e91c91036d0e4d669a7bbd321a8e.

**Comment by daniele-athome** [comment] 2016-04-03 19:05
@webratte it should be fixed now. Kontalk will now save the compressed image to /sdcard/Pictures/Kontalk and it will also read EXIF data to retrieve image orientation.

**Closed by daniele-athome** 2016-04-03 19:05 UTC
Labels: bug
