### ISSUE TITLE
Offline mode indicator

### ISSUE THREAD

**Issue by breversa** [kontalk/androidclient#552] opened 2015-09-20 10:28 UTC
Is there any way to see whether I'm on/offline without opening the menu and checking whether the "go off/online" option exists ?

The title bar would be a very good place for a status indicator, whether text (e.g. "Kontalk (online)"), icon, or simply a color change (from blue to red, but think of the colorblind people ^^)… or a combination of them.

**Comment by daniele-athome** [comment] 2015-09-25 08:29
Changing the background color or adding something to the title can help. I'll set this for the material design release.

**Comment by breversa** [comment] 2015-09-25 11:48
Thanks for taking this into account !
I actually believe an explicit info (= word, not only color, or both) would be better, so that new users won't wonder "Why is the background color suddenly different ?"

**Comment by abika** [comment] 2015-09-25 17:15
simply setting the title to "Kontalk (offline)" would be best imo, if not too long for very small screens

**Comment by daniele-athome** [comment] 2015-11-03 10:38
Duplicate of #481.

**Closed by daniele-athome** 2015-11-03 10:38 UTC
Labels: duplicate
