### ISSUE TITLE
Backup text

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#945] opened 2017-01-30 12:50 UTC
### Expected behavior
Please add an ability to import and export messages that are stored in /data/data. Print-able format would be better but just xml would be nice though.

### Environment

Kontalk version: for new

Device model: any

**Comment by daniele-athome** [comment] 2017-01-30 16:43
Duplicate of #17 and #618.

**Closed by daniele-athome** 2017-01-30 16:43 UTC
Labels: duplicate
