### ISSUE TITLE
Another orientation issue of photos

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#927] opened 2017-01-06 17:08 UTC
### Expected behavior
Correct orientation of pictures

### Actual behavior
Wrong orientation 

### Steps to reproduce
1. Take a picture and send it in original size to yourself
2. Click it to view it in Gallery
3. Use the share button of the Gallery (don't use the share button in Kontalk)
4. Share the picture to yourself
5. The orientation is turned 90°

I have only tested with portrait mode.
With original Camera app and original Gallery app

### Environment

Kontalk version: Google Play 4.0.0 Beta 5 (217)

Android version: 6.0.1
Device model: Sony Xperia M4 Aqua

### Logs

In a few minutes I will send a log and the original photo

**Comment by webratte** [comment] 2017-01-06 17:40
Do you need also the picture from the send folder of Kontalk?

**Comment by webratte** [comment] 2017-01-06 17:47
If I open direct the Gallery (outside of Kontalk) app all pictures will shown correctly.

**Comment by daniele-athome** [comment] 2017-01-08 19:24
Sorry forgot to ask: is the wrong orientation on the thumbnail or on the picture itself?

**Comment by OffifialMITX** [comment] 2017-01-08 19:33
One of my contacts have the same problem, in it's case only the thumbmails.

Am 8. Januar 2017 20:25:00 MEZ, schrieb Daniele Ricci <notifications@github.com>:
>Sorry forgot to ask: is the wrong orientation on the thumbnail or on
>the picture itself?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/927#issuecomment-271172676

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by webratte** [comment] 2017-01-08 20:08
As I sendet this issue it was the thumbnail AND the picture. I'm sure 😠

But now, I don't know why, I can't reproduce it.

Now only the thumbnail is wrong by using the steps I postet.

I will do some more test later.
Maybe I can still reproduce it.

But for now it seems only the thumbnail is wrong.

**Comment by webratte** [comment] 2017-01-08 20:15
I got it.

Between step 1 and step 2 you have to set in settings the Image size to Medium.

**Comment by webratte** [comment] 2017-01-08 20:24
Just one thing I said wrong.
The sendet and received picture is also wrong if I show it in Gallery OUTSIDE of Kontalk

I just did many Tests and lost the control over my thausends of test pictures 😉

**Comment by webratte** [comment] 2017-01-26 17:53
@daniele-athome do you need some more informations from me.
Hopfully you got my logs. If not I can create new logs to help to fix this.

Or why has is thiss issue still the label "pending"?

**Comment by daniele-athome** [comment] 2017-01-27 09:10
Just lack of time, sorry. I've not dismissed it, it will get looked into before 4.0 stable, don't worry :-)

**Comment by daniele-athome** [comment] 2017-05-30 08:29
@webratte a lot of stuff has been improved on this matter lately. It will come out in 4.0.4, I'll close this issue for now, if it happens again (I can't reproduce it anymore), feel free to reopen.

**Closed by daniele-athome** 2017-05-30 08:29 UTC
Labels: bug
