### ISSUE TITLE
Kontalk v3.1.4 crashes when I click on contact in my contact list

### ISSUE THREAD

**Issue by 0strip0nebulosa0** [kontalk/androidclient#672] opened 2016-04-07 11:38 UTC
I have upgraded my Kontalk from 3.1.3 to 3.1.4 using F-Droid app on my Android 4.0.4 phone. It work, but if I click on contact in my contact list then Kontalk crashes.

**Comment by daniele-athome** [comment] 2016-04-07 11:39
I think this is related to #671. Are you on Android 2.3?

**Comment by 0strip0nebulosa0** [comment] 2016-04-07 11:42
No, my Android is v.4.0.4.

**Comment by daniele-athome** [comment] 2016-04-07 11:43
Can you send us a logcat using Catlog from F-Droid please? It would really help.
I'll do some tests in the meantime.

**Comment by 0strip0nebulosa0** [comment] 2016-04-07 12:29
I'm sorry if this is not correct log.
[alogcat20160407-1.txt](https://github.com/kontalk/androidclient/files/208353/alogcat20160407-1.txt)
[alogcat20160407-2.txt](https://github.com/kontalk/androidclient/files/208355/alogcat20160407-2.txt)
[alogcat20160407-3.txt](https://github.com/kontalk/androidclient/files/208354/alogcat20160407-3.txt)

**Comment by daniele-athome** [comment] 2016-04-07 12:32
It's perfect, thank you! Marking as duplicate of #671.

**Closed by daniele-athome** 2016-04-07 12:32 UTC
Labels: bug, duplicate
