### ISSUE TITLE
broken invitation procedure

### ISSUE THREAD

**Issue by shful** [kontalk/androidclient#854] opened 2016-11-05 15:59 UTC
### Expected behavior
An invitation commit should apply in both directions.

### Actual behavior
My girlfried invited me and I committed. Now, she could send messages to me.
I could not send messages back, since an invitation commit from her side was pending.

### Steps to reproduce
1.freshly install Kontalk on two phones. Each users sees two contatcs now: itself plus the other one.
2.send a message to the other user. He is asked for an invitation commit
3.After he committed, the error state is reached.

### Environment
Kontalk version: 3.1.10 (124) from Google Play on 05 Nov 2016

Android version: (please also specify custom ROM name if applicable)
Android 2.3.6 on both sides
Kernel 2.6.35.7 GINGERBREAD.XWJW6 on both sides

Device model:
Samsung Galaxy S i9000 on both sides

### Other
Remark: After rebooting her phone (which could send messages), the invitation became lost for *both* directions. There also seems no way in the GUI to renew the invitation.

**Comment by daniele-athome** [comment] 2016-11-06 14:50
Thanks for reporting. Invitation workflow was subjected to serious refactoring in version 4.0 and it still has a few rough edges to be fixed (they are currently being fixed and they will be before 4.0 final release). I'll keep this open but I'll say let's wait for 4.0 and see. Please see issue #179 for latest alpha if you feel like testing :-)

**Comment by daniele-athome** [comment] 2016-11-15 21:14
I was analyzing this issue in more detail and I realize this shouldn't happen. A preemptive allowance is sent before requesting an invitation right to cover this scenario: this way, as soon as the other contact approves the request, the requester can already receive messages without having to accept. I've just tested this scenario (in both directions, including the reboot test you mentioned) with version 4.0 and it works correctly. As I said, several refactorings were done to the invitation workflow.

I'm going to close this issue now since you can't reproduce it anymore (because you can chat with each other now), but please feel free to open it again if you can reproduce it with other users. Please send us a logcat (using Catlog from Play Store) right after reproducing the bug, possibly from both devices.

**Closed by daniele-athome** 2016-11-15 21:14 UTC
Labels: invalid
