### ISSUE TITLE
Allow emojis in status message

### ISSUE THREAD

**Issue by Manizuca** [kontalk/androidclient#624] opened 2016-01-15 02:52 UTC
Hi, from today i cannot connect anymore to the kontalk server. The last time i sent/received a message was this tuesday, but I think I remember that yesterday i checked if a friend was online... not really sure.

Im using kontalk client v3.1.1 from fdroid in a Moto G (2013) with OmniRom 4.4.4.

Logcat is full of the error below
```
V/MessageCenterService(27497): connection created.
W/aptiveServerPingManager(27497): Setting alarm for next ping to 90000 ms (real 90000 ms)
V/MessageCenterService(27497): authenticated!
W/aptiveServerPingManager(27497): Setting alarm for next ping to 90000 ms (real 89750 ms)
W/AbstractXMPPConnection(27497): Connection closed with error
W/AbstractXMPPConnection(27497): java.io.EOFException
W/AbstractXMPPConnection(27497): 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:169)
W/AbstractXMPPConnection(27497): 	at java.io.InputStreamReader.read(InputStreamReader.java:233)
W/AbstractXMPPConnection(27497): 	at java.io.BufferedReader.read(BufferedReader.java:325)
W/AbstractXMPPConnection(27497): 	at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1506)
W/AbstractXMPPConnection(27497): 	at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:986)
W/AbstractXMPPConnection(27497): 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:346)
W/AbstractXMPPConnection(27497): 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:310)
W/AbstractXMPPConnection(27497): 	at org.kontalk.client.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1174)
W/AbstractXMPPConnection(27497): 	at org.kontalk.client.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:944)
W/AbstractXMPPConnection(27497): 	at org.kontalk.client.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:959)
W/AbstractXMPPConnection(27497): 	at java.lang.Thread.run(Thread.java:841)
W/MessageCenterService(27497): connection closed with error
W/MessageCenterService(27497): java.io.EOFException
W/MessageCenterService(27497): 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:169)
W/MessageCenterService(27497): 	at java.io.InputStreamReader.read(InputStreamReader.java:233)
W/MessageCenterService(27497): 	at java.io.BufferedReader.read(BufferedReader.java:325)
W/MessageCenterService(27497): 	at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1506)
W/MessageCenterService(27497): 	at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:986)
W/MessageCenterService(27497): 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:346)
W/MessageCenterService(27497): 	at org.kxml2.io.KXmlParser.next(KXmlParser.java:310)
W/MessageCenterService(27497): 	at org.kontalk.client.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1174)
W/MessageCenterService(27497): 	at org.kontalk.client.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:944)
W/MessageCenterService(27497): 	at org.kontalk.client.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:959)
W/MessageCenterService(27497): 	at java.lang.Thread.run(Thread.java:841)
D/MessageCenterService(27497): using server beta.kontalk.net
```
Thanks

**Comment by daniele-athome** [comment] 2016-01-15 09:29
Thanks for reporting. The server is indeed complaining about not allowed characters in the XML stream. I'm investigating on the server side.

**Comment by daniele-athome** [comment] 2016-01-15 09:49
Some questions before sending you a debug apk.

1. Does this happen right after login?
2. Have you got encryption enabled in settings?
3. Can't you even receive or is it just sending that stopped working?
4. I can see from the logs that the app goes through authentication, but there is no timestamps in the logs. How much time pass between authentication and disconnection?

**Comment by daniele-athome** [comment] 2016-01-15 09:56
In the meantime, I've restored tigase-xmltools to the 2016-01-07 snapshot to see if it works again.
However, I've contacted other people and no one is having this issue, so it might be related to your device/firmware/custom OS. I suspect it might be related to the your version of the XML library. We'll keep investigating a bit more, I want to know what XML your device is generating.

**Comment by daniele-athome** [comment] 2016-01-15 09:58
A sidenote on XML generation: XML is generated by Smack exclusively IIRC, so it's not the platform. I'll keep investigating.

**Comment by daniele-athome** [comment] 2016-01-15 10:11
I found out the cause. If you include in your status an emoji it will break the XML parser on the server. In the meantime, please remove all emojis from your status message. I think I can handle this with a fix on the client side.

**Comment by daniele-athome** [comment] 2016-01-15 11:00
Ok can't be solved on the client :-(
https://projects.tigase.org/issues/3838

**Comment by Manizuca** [comment] 2016-01-15 16:07
Thanks Daniele, now i can connect without the emoji in my status message. The client was draining my battery trying to connect, now all seems normal, although i like to use emojis

Cheers

**Comment by daniele-athome** [comment] 2016-01-16 17:37
Bug has been fixed by the Tigase team! I have to wait until tomorrow morning for the snapshot, then I'll immediately rebuild and restart the server.

**Comment by bliblablubblub** [comment] 2016-01-17 12:00
I have the same problem if i try to send a emoji unencrypted. The client goes the hole time online/offline and doesn't get an working connection until i delete the message with a emoji.

**Comment by daniele-athome** [comment] 2016-01-17 12:11
Yes, thanks I forgot to mention that it happens also for unencrypyed messages. In fact, it happens when any emoji characters goes through the wire.
I will install the patch on the server today.

**Comment by daniele-athome** [comment] 2016-01-17 14:48
Server has been updated and the bug is now fixed.

**Closed by daniele-athome** 2016-01-17 14:48 UTC
Labels: bug
