### ISSUE TITLE
Unable to register (Authentication failure)

### ISSUE THREAD

**Issue by vn971** [kontalk/androidclient#730] opened 2016-05-12 18:56 UTC
Unable to register using the android client, server returns "Authentication failure".

* a confirmation call is being received by my phone, but it does not match the the mask `+xx-xxxxxx????`  In fact, the numbers have 11 letters, like this: +40338630001
* both **4 last letters** and **3 last letters** do not work (001 and 0001 in this example). I made a new attempt (new phone call) each time I tried.
* SMS confirmation fails. The phone receives the 6 letters sent by Nexmo, but the server still responds with "Authentication failure".

Additional notes:
* the device does not have a SIM card - I'm using an external phone to receive calls and SMS-es.
* the IP address I'm using had a successful registration less than 30 minutes before the new registration attempt. It's a different device and a different phone number - only the IP is shared. I'm exactly reproducing the steps that worked for the old device/phone, but on the new device it fails.

**Comment by daniele-athome** [comment] 2016-05-12 20:41
Thanks for reporting. Please send the phone number you're trying to register to devteam at kontalk.org so I can check with Nexmo.

**Comment by vn971** [comment] 2016-05-12 21:08
Thanks for the reply. I've sent the details.
Looking at the call history I also found this (possibly related) fact:
* the first incoming call number was 12-digit
* all subsequent calls were from 11-digit numbers.

**Comment by daniele-athome** [comment] 2016-05-12 21:19
Thanks! It looks like the phone number verification part actually succeeded. After that, there was a server error while processing your public key. Logs have rotated too many times now, can you try registering again tomorrow please?
Also knowing the device brand, model and Android (or mod) version could help (it could probably be some crappy SSL implementation's fault).

**Comment by vn971** [comment] 2016-05-13 17:29
I guess here it goes again:

* I uninstalled the app so all system data & all caches would be lost
* I installed it again (as the first time, from the F-Droid repo). Version 3.1.8.
* I started phone verification, entered the same name and phone
* did not receive a call
* asked for SMS verification and got the 6-digit code. Entered it
* got `Authentication refused` again (or what is the exact wording).

I'm using Samsung SM-T700 (tablet), android version 4.4.2, kernel version 3.4.39.

**Comment by vn971** [comment] 2016-05-13 19:05
In what way is the public key wrong?

**Comment by daniele-athome** [comment] 2016-05-13 19:32
I've inspected the server logs. I don't think it's the public key to be wrong (it s generated by Spongy Castle built into the apk and it works), I think this might be caused by the X.509 certificate the app creates to authenticate to the server. Despite Kontalk uses Spongy Castle to generate it, what sends it to the server is the SSL implementation of the operating system, which is known to be troubling for some Android versions or devices. Kontalk is a borderline case: it injects a custom X.509 extension into the certificate for bundling the PGP public key (it's a trick we do to authenticate using your PGP key but without using it... long story :-).

We don't have a drop-in replacement for a SSL/TLS implementation that we can use right now, but Google has one we install into the system when you install Kontalk from Google Play. Can you try Kontalk from Google Play to verify this? I'd really like to know if it's your (your device's) SSL implementation to be buggy. Thanks!

**Comment by vn971** [comment] 2016-05-15 19:11
I don't like google market, but since you explicitly asked, I tried to install it from there. I got the same error as before though. Steps taken:
* uninstall kontalk from F-droid
* install kontalk from "google play"
* same as previously: enter the phone, name, push "verify", get the code, enter the code, get "*** refused".

Does Kontalk provide a Tox-like user experience, where you don't have phone numbers and all that stuff, just a public key as user ID?

**Comment by daniele-athome** [comment] 2016-05-15 19:41
Thanks @vn971. I did some debug on the server: your certificate doesn't have our custom extension needed for authentication when it reaches the server. There is a bug somewhere (most probably client, but I don't want to point any finger because I'm totally clueless here - nothing wrong on the app side that I can think of - it works for 99% of devices) that I can't fix. I'll have to workaround it.
But this workaround is going to take some time, sorry.

**Comment by daniele-athome** [comment] 2016-05-15 20:18
Merged into #736.

**Closed by daniele-athome** 2016-05-15 20:18 UTC
Labels: bug, duplicate

**Comment by vn971** [comment] 2016-05-15 20:32
@daniele-athome eh, doesn't sound too simple. Will be waiting then, thanks.

**Comment by daniele-athome** [comment] 2016-05-16 08:59
Believe me, having to deal with all possible Android firmwares out there is a **nightmare**. I'm sorry and thanks for your patience.

**Comment by vn971** [comment] 2016-05-19 13:18
Hi!
Sorry for the late reply, I was able to register today, at ~12:00. Thanks!
Will be finally able to use this app since there are 2 kontalk devices around already.:)

**Comment by daniele-athome** [comment] 2016-05-19 13:41
Great! I'm currently looking at this weird bug when sometimes the registration works and some other times it doesn't. I'll continue investigating because yesterday and today a couple of other cases were registered by the server. Thanks for your help!
