### ISSUE TITLE
No ability to send photo to group

### ISSUE THREAD

**Issue by Fohroer** [kontalk/androidclient#1015] opened 2017-06-10 07:45 UTC
### Expected behavior
Sending photo to group after accepting Kontalk from share menu from gallery.

### Actual behavior
Only contacts shown but not groups.

### Steps to reproduce
1. Open gallery and select share on some photo
2. Select Kontalk
3. Only contacts are shown but not groups

### Environment

Kontalk version: latest from F-droid

Android version: 6.0

Device model: Vernee Thor

**Comment by webratte** [comment] 2017-06-10 08:50
Duplicate of https://github.com/kontalk/androidclient/issues/864

**Closed** 2017-06-12 12:11 UTC
Labels: duplicate
