### ISSUE TITLE
Date of last online status

### ISSUE THREAD

**Issue by Fohroer** [kontalk/androidclient#1000] opened 2017-05-14 13:17 UTC
### Expected behavior
Correct date of last online status.

### Actual behavior
Not correct calculation and non every-minute update of calculation.

### Steps to reproduce
Just view contact which isn't online and wait 5 minutes with screen on and Kontalk opened on this contact.

### Environment

Kontalk version: latest from F-droid.

Android version: 6.0

Device model: Vernee thor

![see this](https://cloud.githubusercontent.com/assets/6697344/26034255/b05f7582-38c2-11e7-8928-4815420e8da2.png)

**Comment by daniele-athome** [comment] 2017-05-15 08:45
Duplicate of #378.

**Closed by daniele-athome** 2017-05-15 08:45 UTC
Labels: duplicate

**Comment by Fohroer** [comment] 2017-05-15 18:51
It's not duplicate. It's also a mention of incorrect date. Problem is active even after going to menu and then to contact again. As I remember.

**Comment by daniele-athome** [comment] 2017-05-16 09:47
The time indicated there is not precise, it's an approximation. I mean when it says "1 hour" it means "approximately 1 hour". Is that what you're referring to?

**Comment by Fohroer** [comment] 2017-05-16 19:21
Approximately? Hm, that's a kind of sound. So you can add parameter 'more than 1 hour'. That would be more correct.

**Comment by daniele-athome** [comment] 2017-05-16 19:52
I've been using this to create that string: https://developer.android.com/reference/android/text/format/DateUtils.html#getRelativeDateTimeString(android.content.Context,%20long,%20long,%20long,%20int)

It seems it's not precise enough... I'll investigate some other methods.
