### ISSUE TITLE
Featurerequest: Instantly downlod attachments

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#375] opened 2015-04-02 04:40 UTC
Featurerequest: Instantly downlod attachments by userpreference:

-always
-only in WLAN/WiFi
-never

But only if it's not too complicated to  implement.
It's not the most important feature ;-)

**Comment by daniele-athome** [comment] 2015-04-02 07:18
Duplicate of #34 :-)

**Closed by daniele-athome** 2015-04-02 07:18 UTC
Labels: duplicate

**Comment by webratte** [comment] 2015-04-02 07:27
Oops. :-D
