### ISSUE TITLE
Show images before sending

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#850] opened 2016-10-25 09:06 UTC
I have the problem that both if I share a picture via the share menu or take a photo with Open Camera I don't have the option to proof the image before sending (either I tap the wrong contact or I don't like the photo but it's directly sent).

I think it would be a useful feauture if there was a pop up window with the picture and a question if you want to send this image to that contact.

**Comment by daniele-athome** [comment] 2016-10-25 09:33
Duplicate of #18.

**Closed by daniele-athome** 2016-10-25 09:33 UTC
Labels: duplicate

**Comment by OffifialMITX** [comment] 2016-10-25 12:02
Oh, sorry, it's not easy to find an existing issue using the phone's browser.

**Comment by daniele-athome** [comment] 2016-10-25 14:13
No problem, the fact that you care about opening an issue is already of great help!
