### ISSUE TITLE
Adding XMPP user to chat & XMPP 'personal key not yet verified'

### ISSUE THREAD

**Issue by 2SI3NX** [kontalk/androidclient#1135] opened 2018-01-15 17:58 UTC
2 Issues regarding this:

1. I dont see any way in adding an XMPP user via the app.  The only way i added the user is by sharing "My Personal Key" with the other user that uses XMPP client / jabber ID and he added me.

2. Upon adding me to chat, i received a notification and it said in the chat toaster message: "Personal Key not yet verified"
I pressed Details > accept and it says "unable to find a public key for this user..etc"

Kontalk version: F-Droid 4.1.2

**Comment by 2SI3NX** [comment] 2018-01-15 18:00
Surely there should also be a manual way of entering a XMPP user's public key through the app to invite or accept.

**Comment by daniele-athome** [comment] 2018-02-03 11:22
Hello and thanks for reporting. The first issue is a duplicate of #496.
The second issue should have been fixed in 4.1.3, could you try again please?

**Closed by daniele-athome** 2018-02-03 11:22 UTC
Labels: duplicate

**Comment by webratte** [comment] 2018-02-03 11:41
@daniele_athome I have the feeling you misunderstood the second issue.

A normal xmpp user has not a key which is compatible AFAIK. 

Or I'm wrong?

**Comment by daniele-athome** [comment] 2018-02-03 12:43
@webratte you're right sorry. I thought he was talking about a Kontalk user. So @2SI3NX you have to disabled encryption inside the conversation with that user. While inside the conversation, Menu > uncheck "Encryption".
