### ISSUE TITLE
share with groups

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#907] opened 2016-12-17 22:58 UTC
### Expected behavior
You should be able to share files into the group chat

### Actual behavior
You aren't able to share files into the group chat

### Steps to reproduce
1. Create/join a group
2. Go to any file browser / gallery and share via kontalk
3. You are not able to select a group

### Environment

Kontalk version: 4.0.0 beta4

Android version: 5.1.1

Device model: Neffos C5L

**Comment by webratte** [comment] 2016-12-18 05:15
Duplicate of 
https://github.com/kontalk/androidclient/issues/864

**Closed** 2016-12-18 14:09 UTC
Labels: duplicate
