### ISSUE TITLE
Input field gets out of viewport when message is too long

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#542] opened 2015-08-30 09:59 UTC
Kontalk version:3.1-beta1 (70)
Phone: HTC Desire X
Android: 4.1.1

Steps to reproduce

* Write a message to a receiver who use a older version of Kontalk then you (Yello banner appeares)
* Write now a longer message (more the 5 or 6 lines)
* Now the last line (included the eoticon button) in inputfield will be behind the keyboard.

If you not know what I mean, I can make a screenshot for better understanding.

**Comment by webratte** [comment] 2015-08-30 10:50
Here the screenshot:

![screenshot_2015-08-30-12-03-22](https://cloud.githubusercontent.com/assets/6864851/9566843/a5c81248-4f15-11e5-9fb2-b4d95d0a0a83.png)

**Comment by TheLastProject** [comment] 2015-08-30 21:23
I need to write 11 lines to reproduce the issue, but indeed, the text field does go below the keyboard, but only when there is a yellow "old version" warning. I assume the height of the warnings is not subtracted from the max height of the input field.

**Comment by TheLastProject** [comment] 2015-09-14 21:42
May I ask why you changed the title? This is not about the emoji drawer, the emoji drawer in something I reported in the 3.1 pull request.

**Comment by daniele-athome** [comment] 2015-09-14 21:45
Because I'm an idiot :-) and tired. Thanks for noticing @TheLastProject.

**Comment by TheLastProject** [comment] 2015-09-14 22:00
Just to make absolutely sure, it also only happens when the yellow banner is there ^^

**Comment by daniele-athome** [comment] 2015-09-17 22:11
Closed by 2d08d4b1027f6e3c5099cf451cd76a59bbb03cc7.

**Closed by daniele-athome** 2015-09-17 22:11 UTC
Labels: bug
