### ISSUE TITLE
Emoji set and Keyboard are now only being showed together.

### ISSUE THREAD

**Issue by OffifialMITX** [kontalk/androidclient#1110] opened 2017-11-29 05:37 UTC
This is not a new problem for me. Since I'm using TaskBar both keyboard and emoji set would appear when I vlick on the smiley. However I've been able to easily avoid this problem by closing my keyboard before opening the set.

Now with the new version  (F-Droid) containing the new set both keyboard and emoji bar are being opened when the smiley is being clicked on. I'm on Stock Android 5.1.1.

![](https://i.imgur.com/ns51ixT.png)

**Comment by daniele-athome** [comment] 2017-12-01 13:34
Thanks for reporting. This is actually a long-standing issue that's been happening to several other projects using the emoji-panel-over-keyboard approach (it also happened to me with emojicon and with this lib, but I've never been able to reproduce it, it happens randomly). It doesn't work on some devices because it's a workaround to trick the OS to do what we want. I'll investigate the issue together with the library's author.

Does it happen every time for you? Do you have a precise way to reproduce it?

**Comment by OffifialMITX** [comment] 2017-12-01 16:55
Yes and yes.
The process is simple

1. Install TaskBar https://f-droid.org/app/com.farmerbb.taskbar.

2. Launch it.

3. activate it in the upper right corner, any setting does not affect anything though you might want to go to the general settings and set position on top.

On December 1, 2017 2:34:01 PM GMT+01:00, Daniele Ricci <notifications@github.com> wrote:
>Thanks for reporting. This is actually a long-standing issue that's
>been happening to several other projects using the
>emoji-panel-over-keyboard approach (it also happened to me with
>emojicon and with this lib, but I've never been able to reproduce it,
>it happens randomly). It doesn't work on some devices because it's a
>workaround to trick the OS to do what we want. I'll investigate the
>issue together with the library's author.
>
>Does it happen every time for you? Do you have a precise way to
>reproduce it?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/1110#issuecomment-348495741

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by OffifialMITX** [comment] 2017-12-01 16:57
This does npt work with other apps that use the screen overlay permission.

On December 1, 2017 2:34:01 PM GMT+01:00, Daniele Ricci <notifications@github.com> wrote:
>Thanks for reporting. This is actually a long-standing issue that's
>been happening to several other projects using the
>emoji-panel-over-keyboard approach (it also happened to me with
>emojicon and with this lib, but I've never been able to reproduce it,
>it happens randomly). It doesn't work on some devices because it's a
>workaround to trick the OS to do what we want. I'll investigate the
>issue together with the library's author.
>
>Does it happen every time for you? Do you have a precise way to
>reproduce it?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/1110#issuecomment-348495741

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment] 2017-12-02 11:12
We don't use the screen overlay permission.
I'll do some tests.

**Comment by OffifialMITX** [comment] 2017-12-02 11:23
I know Kontalk doesn't, I meant that other apps using this technique donpt interfere Kontalk's functionality.

On December 2, 2017 12:12:53 PM GMT+01:00, Daniele Ricci <notifications@github.com> wrote:
>We don't use the screen overlay permission.
>I'll do some tests.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kontalk/androidclient/issues/1110#issuecomment-348685124

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by daniele-athome** [comment] 2017-12-03 19:26
I forked the library and I've been doing some tests, unfortunately with no success :-(
I've opened an [issue upstream](vanniktech/Emoji#224), he might be able to help us.

**Comment by tetris4** [comment] 2017-12-04 12:01
@daniele-athome that link is broken.

**Comment by daniele-athome** [comment] 2017-12-04 13:18
Sorry. Fixed.

**Comment by daniele-athome** [comment] 2019-04-16 18:10
Emoji 0.6.0 was release by @vanniktech some time ago which should include a fix for this. Closing now, feel free to reopen after the next version comes out.

**Closed by daniele-athome** 2019-04-16 18:10 UTC
Labels: bug

**Comment by OffifialMITX** [comment] 2019-06-04 17:07
So, I was going through my emails, found this and tried out with the current version 4.2.0. Still the same thing on my now newer Moto E4 Plus with exactly the same results.
![](https://i.imgur.com/KQbTH0R.png)

**Comment by OffifialMITX** [comment] 2019-06-04 17:08
(Dtock Android 7.1.1)

**Comment by daniele-athome** [comment] 2019-06-10 19:11
@OffifialMITX thanks for reporting, hopefully 4.3.0 will be released in a couple of weeks. Sorry, I've been busy with other stuff and I'm also working on [the OMEMO branch](https://github.com/kontalk/androidclient/pull/1256).
