### ISSUE TITLE
Group creation command ignored

### ISSUE THREAD

**Issue by 115ek** [kontalk/androidclient#1067] opened 2017-09-11 19:56 UTC
### Expected behavior
open new group
added members should get notification about new group (they should see them in their list)
### Actual behavior
added members don't get notification and can't see group
### Steps to reproduce
1. open new group, add members
2. members can't see the group (don't get notification)

### Environment

Kontalk version: F-Droid 8033bbbf9287a92d7cd74312e6b5bda764cd040f

Android version: 6.0.1 (Sony Stock) 7.1.2 (LineageOS) 6.0.1 (CyanogenMod)

Device model: Xperia Z3 compact, S3 Mini, Xperia Pro

### Other

already existing groups are still working - but removing and readding a member results in the same problem
tried opening groups and adding members in all variations
admin who adds the members doesn't get any errors

**Comment by daniele-athome** [comment] 2017-09-24 09:36
Thanks for reporting. I don't understand if the problem is the notification of a new group not appearing or the new group not appearing in the chat list. The former is expected, the latter is not.

**Comment by 115ek** [comment] 2017-09-24 10:38
The problem was the new group not appearing in the chat list. So it is an unexpected issue but worked in earlier versions. 
If Alice adds Bob in a group, the group doesn't appear in Bobs chatlist. Furthermore Bob can't participate in the group (can't write or read). He doesn't even see that he's a member of the group.
At the other side Alice doesn't notice anything: she's still thinking that Bob was successful added and receives her messages.

**Comment by daniele-athome** [comment] 2017-09-25 16:17
Can you send me a debug log of both devices (Alice and Bob) while doing this test? It would help having a debug log also from a third device (another member Charlie). Thank you!

**Comment by 115ek** [comment] 2017-09-26 20:23
I took some logs with the inbuilt logger.
For Alice, who creates the group, i got:
```E/MessagesProvider: unable to update thread metadata (threadId not found)```

And for Bob, who doesn't get a notification:
```W/MessageCenterService: invalid or unauthorized group command```

Thats all interesting I've got.

**Comment by 115ek** [comment] 2017-09-27 16:04
I sent a mail to devteam (at) kontalk.org. Is there anything else I can do? What do mean with a third device? Should Charlie also be a member of the created group?

**Comment by daniele-athome** [comment] 2017-09-28 13:55
I got the logs and I was able to reproduce the issue, thank you! I'll release a hotfix today.

**Comment by daniele-athome** [comment] 2017-09-28 13:57
Fixed in kontalk/client-common-java@9783d60a20e74ccfd460ef1a24b19a70e825d685.

**Closed by daniele-athome** 2017-09-28 13:57 UTC
Labels: bug

**Comment by 115ek** [comment] 2017-09-28 17:06
Works :)
