### ISSUE TITLE
kontalk not able to connect to server

### ISSUE THREAD

**Issue by freddii** [kontalk/androidclient#626] opened 2016-01-15 22:10 UTC
The Kontalk messanger on my android device stopped working 14-1-16 and is not working till now.
is there a kontalk server down?
i am also not able to update the serverlist in settings. 
last time i updated the serverlist was on 6-3-15.
i am using kontalk version 3.1.1 (78) on android 4.2.2.

a friend of me is having the same problem..

**Comment by daniele-athome** [comment] 2016-01-15 22:17
Duplicate of #624. Sorry but it needs fixing on the server so it might take a couple of days. The workaround is described in the other issue.

**Comment by freddii** [comment] 2016-01-15 22:18
ok thx.

**Closed** 2016-01-15 22:17 UTC
Labels: duplicate
