### ISSUE TITLE
Member "readded" to group but can't communicate with admin

### ISSUE THREAD

**Issue by pamoreno** [kontalk/androidclient#1173] opened 2018-04-16 17:56 UTC
### Situation
I'm admin of a group chat with 10 users. User X needs to be re-added for one of the following reasons:
a) it uninstalled Kontalk,
b) it left the group chat and wants to join again.

I remove user X, if a). Later, I add the user.

### Expected behavior
All members in the group should be able to communicate. Group members list should show them all. Group info should show 10 members.

### Actual behavior
For the example case, group information shows 9 users in the group. The 10th user does not appear at the members list. From the tests I've done, speaking with user X and other users, I have no strong conclusion. Most of the times, user X can see the group and can send messages but I, and only I, can't read them, nor user X can see mine (as if those messages are not being delivered between us). Some times, the behaviour is shared and another user reports the same. And I remember that at least one time worked.

It does not matter how many times I readd the user. Group members list does not show it, group info shows 9 users.

I have tried with and without key regeneration, and most of the times, it's the same behaviour.

### Steps to reproduce
1. Create a group chat with, in my case, 10 users.
2. One user uninstalls kontalk (in a dirty way) and reinstalls it, creating new keys.
3. Add user to the group chat.

There are many variants to reproduce the issue: the user can export keys before uninstalling kontalk, or it can unregister from the network, or none (dirty way). From any of those, the user can be added to the group before exchanging keys with all the other members, or after, or in the middle of the exchanges.

### Environment

Kontalk version: F-Droid

Android version: 4.4.4 (CyanogenMod 11) (had to downgrade when #1112 came out)

Device model: Samsung GT-I8260

### Other

Maybe related to #1127 and/or #1171?.

**Comment by daniele-athome** [comment] 2018-07-22 19:51
Duplicate of #1189. I've inadvertently opened the same bug a few weeks later and fixed it :-) thanks for reporting!

**Closed by daniele-athome** 2018-07-22 19:51 UTC
Labels: duplicate
