### ISSUE TITLE
Previously authorized person shows as "verified" although person is not verified anymore

### ISSUE THREAD

**Issue by StefanBrand** [kontalk/androidclient#874] opened 2016-12-04 12:39 UTC
### Expected behavior
The ✅ should turn into ❌ when a person's key changes.

### Actual behavior
There is a red bar that blocks the text field in private chats, and a pop-up-fade-out notification in group chats, but the group info shows the ✅ , and the info pop-up of that person shows "verified" in green letters.

### Steps to reproduce
1. Open a group chat with 4 people, including you. All of them are verified.
2. One person's key changes.
3. Open group info. That person is still marked with ✅ .

### Environment

Kontalk version: Beta1-212

Android version: Android 4.4.2

Device model: Fairphone 1

**Comment by daniele-athome** [comment] 2016-12-04 19:54
Just to be sure: is the user changing his/her key while the group info window is open? Automatic update of those information is not implemented yet (if that's your case).

**Comment by StefanBrand** [comment] 2016-12-04 22:53
No, the group chat window was not open. This morning I opened Kontalk because the person had sent me a message. I then saw the red bar notifying me of the changed identity. Afterwards I opened the group chat.
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 4. Dezember 2016 20:54:48 MEZ, schrieb Daniele Ricci <notifications@github.com>:
>Just to be sure: is the user changing his/her key while the group info
>window is open? Automatic update of those information is not
>implemented yet (if that's your case).

**Comment by daniele-athome** [comment] 2016-12-05 09:18
Ok thanks, I'll try to reproduce it tonight and gather some more information to fix it.

**Comment by daniele-athome** [comment] 2016-12-06 21:26
I can't reproduce it. If you have root access, please do the following:

* force stop Kontalk from system settings
* delete the file: `/data/data/org.kontalk/databases/keys.db`
* try again to reproduce the issue

Please note that you'll lose trusted keys; don't worry, Kontalk will retrieve them again and just ask you if you trust them again; in case of issues please refresh Kontalk contact list: New chat > Menu > Refresh)

**Comment by StefanBrand** [comment] 2016-12-08 17:34
I might have time to reproduce it with a friend next Tuesday, but please 
understand that it's quite inconvenient for the other person and don't 
count on it. :)

Am 06.12.2016 um 22:26 schrieb Daniele Ricci:

**Comment by daniele-athome** [comment] 2016-12-08 19:13
No problem. I'll do some more tests in the meantime, I hope I can find new ways to try to reproduce it. Just a reminder note: you don't need to register from scratch to get a new key, there is a setting inside "maintenance" to renew your personal key.

**Comment by StefanBrand** [comment] 2016-12-08 21:55
If I export my key and then renew it, will I be able to import the old 
key again and thus set back my key to what it was before renewing it?

Am 08.12.2016 um 20:13 schrieb Daniele Ricci:

**Comment by daniele-athome** [comment] 2016-12-09 12:31
You're right, no because renewing your key makes the old one to be revoked, thus not usable anymore, ever. The only way to regain access to your old key is to delete your account every time. Even so, I've just discovered a bug that makes the app crash on importing a key in this situation.

Among other things, I'm releasing beta3 today so we can test this more thoroughly.

**Comment by daniele-athome** [comment] 2017-01-02 19:54
@StefanBrand did you have any chance of bumping again into this issue with beta5? It should be on F-Droid by now.

**Comment by StefanBrand** [comment] 2017-01-02 22:05
I've upgraded through F-Droid (well, uninstalled and reinstalled after 
using basic.apk. Importing the key worked flawlessly.) I'll try to make 
my fellow testers upgrade too!


Am 02.01.2017 um 20:54 schrieb Daniele Ricci:

**Comment by daniele-athome** [comment] 2017-01-21 11:26
I'm releasing beta6 soon so I'm now closing this since I've fixed several issues concerning subscription and key updates. Feel free to reopen it or open a new one if beta6 has issues. Thanks!

**Closed by daniele-athome** 2017-01-21 11:26 UTC
Labels: bug

**Comment by StefanBrand** [comment] 2017-01-21 12:36
Sorry we didn't get to testing this anymore...
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 21. Januar 2017 12:26:40 MEZ schrieb Daniele Ricci <notifications@github.com>:
>I'm releasing beta6 soon so I'm now closing this since I've fixed
>several issues concerning subscription and key updates. Feel free to
>reopen it or open a new one if beta6 has issues. Thanks!

**Comment by daniele-athome** [comment] 2017-01-21 12:38
No problem, if the issue is still there it will appear again (hopefully not).
