### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by h-2** [kontalk/androidclient#287] opened 2015-02-03 12:51 UTC
Well, its not super important, but it would be very nice to have :smile:

**Comment by daniele-athome** [comment] 2015-02-03 12:53
Duplicate of #41.

**Closed by daniele-athome** 2015-02-03 12:53 UTC
Labels: duplicate, enhancement

**Comment by h-2** [comment] 2015-02-03 13:13
wow, it even had the same name :flushed: sorry for duplicate.

**Comment by daniele-athome** [comment] 2015-02-03 13:25
No problem ;)
