### ISSUE TITLE
Send Video

### ISSUE THREAD

**Issue by svrnwnsch** [kontalk/androidclient#577] opened 2015-10-17 00:19 UTC
As voice files can be transferred already via kontalk 3, is it possible to send video or general files via kontalk too?

**Comment by webratte** [comment] 2015-10-17 09:35
There is already a open issue for this. 
So it seams a duplicate of  #26 ;-)

**Comment by daniele-athome** [comment] 2015-10-17 14:37
It is indeed, thanks @webratte.

**Closed by daniele-athome** 2015-10-17 14:37 UTC
Labels: duplicate
