### ISSUE TITLE
Always off encryption for Juick

### ISSUE THREAD

**Issue by Buranek** [kontalk/androidclient#914] opened 2016-12-24 17:27 UTC
Feature request

### Expected behavior
There is a jabber bot juick@juick.com which allows you to have blog which you can control via Jabber. And the connection with this bot is always unencrypted. So I think I need an option to disable encryption for just one contact.

### Environment

Kontalk version: F-Droid Stable

Android version: 5.1

Device model: Oukitel U7 PRO

**Comment by daniele-athome** [comment] 2016-12-26 19:30
Duplicate of #271.

**Closed by daniele-athome** 2016-12-26 19:30 UTC
Labels: duplicate
