### ISSUE TITLE
 No connection on fresh install & registration

### ISSUE THREAD

**Issue by keynlotepan** [kontalk/androidclient#747] opened 2016-05-27 09:03 UTC
Yesterday I happily discovered Kontalk on F-Droid. Exactly the app I was looking for long time as I do not want to run my conversations via Facebook. Thanks a lot!

After installation/registrations (on CM11) I was able to have conversations with myself. When my wife came home she also installed / registered (on CM13). We both were running Kontalk in foreground without any pause. But initially we were not able to communicate. After I manually switched offline / online via Kontalk menu a first part of the functions (discover person in contact list, send messages, receive messages) worked (I do not remember which part, sorry), but only after she performed manual reconnection, too, everything worked fine until now.

This does not look like an important issue since it only occurs during first use. But on the other hand "first use" is an important use case. Many people might drop Kontalk swiftly if it does not seem to work from the very beginning. Most users do not have the idea to perform experiments like manual reconnection, especially since this menu item is not accessible from the conversation panel, which is open when they unsuccessfully try to communicate.

**Comment by daniele-athome** [comment] 2016-05-27 09:11
Thanks for your interest in the project and most importantly thanks for reporting this issue. Since you have CM, you should also have root access. Would you mind trying to reproduce the issue and send us a system log by using CatLog (also on F-Droid)? Also it'll be of great help to know in what way texting to your wife didn't work. Did you get some error message or your messages just got stuck with pending status (clock icon)?

**Comment by keynlotepan** [comment] 2016-05-27 09:25
Of course I would like to support you with test runs. But how to reproduce this test case of an initial registration? Do we both have to unsubscribe/uninstall and resubscribe/install?
At the moment this is not possible since my wife is on a business trip. Maybe on Sunday we will find  time for such a test.

**Comment by daniele-athome** [comment] 2016-05-27 09:30
> Do we both have to unsubscribe/uninstall and resubscribe/install?

Unfortunately yes, it's the only way, unless you have another device with another SIM card to test on. No rush though, take your time. Just please try it with a fresh install so everything will be clean.

**Comment by keynlotepan** [comment] 2016-05-30 07:25
Test will follow in two weeks due to holiday travel. Sorry. [Burglary not recommended, appartment is inhabited meanwhile].

**Comment by daniele-athome** [comment] 2016-05-30 07:28
Absolutely, no need for apologies. Have a great time!

**Comment by keynlotepan** [comment] 2016-06-18 07:34
Back from holiday I must tell you that my wife and me have separated after decades. It's no joke, it's the very sad truth. So we are not going to perform the test and my only contact on Kontalk has disappeared.

**Comment by daniele-athome** [comment] 2016-06-18 10:40
Oh my god I'm so sorry! I really don't know what to say... thanks anyway though.

**Comment by daniele-athome** [comment] 2016-09-04 16:12
I'm going to close this to keep the issues list clean, feel free to report back if you will or can. Sorry again for your loss.

**Closed by daniele-athome** 2016-09-04 16:12 UTC
Labels: invalid
