### ISSUE TITLE
Show groups when sharing files

### ISSUE THREAD

**Issue by Megver83** [kontalk/androidclient#942] opened 2017-01-29 01:14 UTC
### Expected behavior
Share anything, e.g. an image, and show all chats (groups and contacts)

### Actual behavior
Share anything, e.g. an image, but it only shows contacts, so to share an image in a group you have to do it from Kontalk

### Steps to reproduce
1. Open any app (e.g. Gallery)
2. Share the file
3. Select Kontalk

**Comment by webratte** [comment] 2017-01-29 06:53
Thank you for reporting it.
But there is a open issue.

So it's a duplicate of https://github.com/kontalk/androidclient/issues/864

**Closed** 2017-01-29 10:25 UTC
Labels: duplicate
