### ISSUE TITLE
Can't get any contact's connection updates without "proper" Internet connection

### ISSUE THREAD

**Issue by EVAnaRkISTO** [kontalk/androidclient#1041] opened 2017-07-20 20:34 UTC
### Expected behavior
Whenever Kontalk has connection to the Internet it should be able to obtain contact's connection updates and messages.

### Actual behavior
Using RepWifi (https://redmine.replicant.us/projects/replicant/wiki/WifiAdapter) with an USB Wifi Adapter (+ OTG) in Replicant 6, without WiFi proprietary firmwares (https://blog.fossencdi.org/nonfree-firmware-android.html) and cellular data disabled, I can surf the web, but I get no contact's connection updates and/or messages, even restarting Kontalk's Messaging Centre. Seems like Kontalk relays on Android's Internet capabilities and doesn't check there's actually connection to the Internet.

### Steps to reproduce
1. Install Replicant 6. If you have installed proprietary firmwares, remove them (at least Wifi).
2. Connect a supported USB Wifi Adapter with and OTG cable (https://redmine.replicant.us/projects/replicant/wiki/WifiAdapter).
3. Start RepWifi and connect to the WiFi you want and check you can surf the web.
4. Restart Kontalk's Messaging Centre.

### Environment

Kontalk version: 4.0.4 (F-Droid)

Android version: Replicant 6.0 + Technoethical N150 Mini Wireless USB Adapter + Technoethical Nano OTG Adapter, with Bluetooth and GPS proprietary firmwares installed. WiFi proprietary firmwares removed (and phone rebooted) and cellular data disabled.

Device model: Samnsung Galaxy S3 (GT-i9300)

### Logs

I have no way to get logs because adapter uses the port I would have to use to "adb" to the device.

### Other

Seems to happen the same with F-Droid (https://redmine.replicant.us/issues/1792)

**Comment by daniele-athome** [comment] 2017-07-20 20:42
I believe the issue is actually been fixed in Replicant (and it's their issue really), isn't it?

**Closed** 2017-07-20 20:42 UTC
Labels: invalid

**Comment by EVAnaRkISTO** [comment] 2017-07-21 07:54
I guess you're right. I didn't read https://redmine.replicant.us/issues/1792 beyond the beginning because a lot of programming terms seemed gibberish to me: I only programmed in Visual Basic a long time ago and did a little C programming, so I'm not a programmer.

I apologize to you for not reading information fully.

Thanks for your great work

**Comment by daniele-athome** [comment] 2017-07-21 08:09
No problem. I'm here to help :-)
