### ISSUE TITLE
Export/import groups and chats 

### ISSUE THREAD

**Issue by jhoc2000** [kontalk/androidclient#1286] opened 2020-02-29 01:16 UTC
### Expected 
When importing a Kontalk key to a new device one has to create the chats and groups all over again if that one is the groups' owner. 

There should be a way for a user to export their chats and groups when they intend to switch their Kontalk key to another device. For example, "Export Kontalk chats and groups" . 

Once one has successfully imported a Kontalk key onto another device then one should be able to "Import Kontalk chats and groups. If this is available then one doesn't have to restart one's chats and, more importantly, delete and recreate the groups that one owns. 

### Actual behavior
One changes a device by importing an exported Kontalk key but one has to restart the chats and recreate the groups that one owns. This is very annoying not only to the owner but also to those already on the groups. 

### Steps to reproduce
1. Export Kontalk key 
2. Change device 
3. Import Kontalk key 
4. One has lost all his or her chat contacts and groups that one owns.

### Environment

Kontalk version: 4.3.1 (440) from F-Droid

Android version: 9 LineageOS 16.0-20200223-NIGHTLY-beryllium

Device model: Xiaomi Pocophone F1

### Logs
NA
### Other

NA

**Comment by daniele-athome** [comment] 2020-03-19 18:34
Duplicate of #17.
I know this is a really needed, long overdue feature, especially for groups. As a quick workaround, _only if you're not the admin of a group_, you can ask the admin to add you (a user can be added multiple times in a group at any time).

**Closed by daniele-athome** 2020-03-19 18:34 UTC
Labels: duplicate
