### ISSUE TITLE
Feature request: Fetch Jabber avatars

### ISSUE THREAD

**Issue by Fohroer** [kontalk/androidclient#1017] opened 2017-06-10 07:49 UTC
### Expected behavior
Fetch Jabber avatars from Jabber server or at least from phone-book. Or ability to set avatar to contact inside program.

**Comment by webratte** [comment] 2017-06-10 08:54
Probably duplicate of https://github.com/kontalk/androidclient/issues/826

**Comment by daniele-athome** [comment] 2017-06-12 12:13
Indeed @webratte. Thank you.

@Fohroer the avatar is currently retrieved only from the phonebook, except for some rare cases e.g. Facebook which doesn't allow 3rd party apps to read their avatar (i.e. only Android Contacts is allowed).

**Closed by daniele-athome** 2017-06-12 12:13 UTC
Labels: duplicate

**Comment by Fohroer** [comment] 2017-06-13 18:14
I mean Jabber contacts from the regular Jabber servers. It will be good to fetch avatars if XMPP field is filled for phone-book contact. Understand?

**Comment by daniele-athome** [comment] 2017-06-18 11:36
Yes that's what I meant. I meant: currently avatars are retrieved only from Android contacts pictures, we'll support avatars requested to the server, that's included in #826.
