### ISSUE TITLE
Load more messages not correctly hidden in search

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#642] opened 2016-02-01 22:12 UTC
How to reproduce:
1. Search for one of the first messages
2. Tap search result
3. Scroll up

Expected result:
No "Load more messages" button as we're all the way at the start.

Actual result:
Load more messages button which, when pressed, loads the newest messages and prepends them.

On that note, when the button is correctly nonexistent (in an existing conversations without search when no more messages are available) it still takes space (white padding above very first message in conversation)

**Comment by daniele-athome** [comment] 2016-02-02 09:43
This bug should have been fixed on 3.1.3. I can see 3.1.3 was built just yesterday, can you confirm it happens also in 3.1.3? Please be aware that when you open a conversation from a search, the "Load more messages" button is not visible because the whole conversation is loaded.

**Comment by TheLastProject** [comment] 2016-02-02 12:57
This happens in 3.1.3 specifically. If you scroll up all the way with the scrollbar and then with your finger a bit more, the "Load More Messages" button does appear in the message list on search.

**Comment by daniele-athome** [comment] 2016-02-02 14:06
Exactly, that's because when searching the conversation is fully loaded, no pagination is activated, that's why the load more messages button is not visible.
About the padding when the button is invisible: it requires a re-layout (takes time and power; hiding the button is not enough so I thought it wouldn't be much of an issue... or is it?).

**Comment by TheLastProject** [comment] 2016-02-02 14:08
Well, the problem is that the button IS visible

**Comment by TheLastProject** [comment] 2016-02-02 14:10
Is the thread you are testing it on actually long enough to paginate? It only appears in long conversations.

**Comment by daniele-athome** [comment] 2016-02-02 14:11
Actually the problem is I am totally screwed up :-) ok now I see it... sorry. I'm not so good at multitasking.

**Closed** 2016-02-07 18:06 UTC
Labels: bug
