### ISSUE TITLE
quick reply

### ISSUE THREAD

**Issue by keshto** [kontalk/androidclient#948] opened 2017-02-04 21:55 UTC
using the fdroid version when a message is received there are "Read" and "Call" quick actions. It would be nice to see a quick reply like most modern messaging apps.

**Comment by webratte** [comment] 2017-02-05 06:04
Hi,
it seems your not the only one.
I think it's a duplicate of https://github.com/kontalk/androidclient/issues/629 and https://github.com/kontalk/androidclient/issues/630 😉

**Comment by keshto** [comment] 2017-02-05 07:16
yes it is a duplicate. sorry should have searched first.

**Closed** 2017-02-05 12:54 UTC
Labels: duplicate
