### ISSUE TITLE
show groups when sharing media

### ISSUE THREAD

**Issue by Megver83** [kontalk/androidclient#980] opened 2017-03-17 16:58 UTC
This is an example of the feature Kontalk should implement.

### Expected behavior
Share anything, like a photo. I go to Gallery, and share it to Kontalk, and when Kontalk opens see contacts and groups

### Actual behavior
Share anything, like a photo. I go to Gallery, and share it to Kontalk, and when Kontalk opens it only shows my contacts, not the groups, so I have to share photos fom kontalk for the groups

### Steps to reproduce
1. Go to your gallery app
2. Put the share option
3. Select Kontalk
4. You won't see groups, only your contacts

**Comment by webratte** [comment] 2017-03-17 17:03
Duplicate of https://github.com/kontalk/androidclient/issues/864

**Closed** 2017-03-17 19:25 UTC
Labels: duplicate
